######################################################################
# Automatically generated by qmake (3.0) Wed Nov 5 16:43:00 2014
######################################################################

TEMPLATE = app
TARGET = gapp
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += Advisor.h
SOURCES += Advisor.cpp main.cpp
