######################################################################
# Automatically generated by qmake (3.0) Wed Nov 5 12:50:11 2014
######################################################################

TEMPLATE = app
TARGET = gapp
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += Advisor.h button.h
SOURCES += Advisor.cpp button.cpp main.cpp
